name: Sitemap Creator Stable
description: GitHub Action 🚀 for creating and updating sitemaps in your repository.
author: 鸭鸭「カモ」(@DuckDuckStudio)

branding:
  color: yellow
  icon: book

inputs:
  location:
    required: false
    description: 网站地图的存放位置
    default: "./sitemap.xml"

  token:
    required: false
    description: 用于创建更新网站地图的拉取请求的 Token
    default: ${{ github.token }}

  timezone:
    required: false
    description: 设置生成时使用的时区
    default: "Asia/Shanghai"

  basic_link:
    required: false
    description: 指向你网站的基础链接
    default: https://${{ github.event.repository.owner.login }}.github.io/${{ github.event.repository.name }}

  file_type:
    required: false
    description: 网页文件的类型
    default: "html,md"

  ignore_file:
    required: false
    description: 指定哪些文件不包含在网站地图中
    default: "啥都没有" # 应该不会有人要这个，留空会忽略所有文件

  website_path:
    required: true
    description: 你的网站内容的位置
    default: "./"

  base_branch:
    required: false
    description: 仓库主分支
    default: main

  debug:
    required: false
    description: 控制调试输出的开关
    default: false

  label:
    required: false
    description: 创建拉取请求时添加的标签

  auto_merge:
    required: false
    description: 设置启用自动合并的类型 (不指定则不启用自动合并，可以使用 merge、rebase、squash)

  update:
    required: false
    description: 指定更新网站地图的方式 (直接提交或拉取请求)
    default: 拉取请求

  reviewer:
    required: false
    description: 创建拉取请求时指定的审查者

  author_name:
    required: false
    description: 更新提交的撰写者名
    default: "github-actions[bot]"

  author_email:
    required: false
    description: 更新提交的撰写者邮箱
    default: "41898282+github-actions[bot]@users.noreply.github.com"

runs:
  using: node20
  main: index.js
