name: "✨ 优化建议"
title: "[Pref]: "
description: 提出改进建议 (这并不意味着你必须实现它)。
labels: ["优化","DEV-需要注意"]
body:
  - type: markdown
    attributes:
      value: 感谢您抽出时间与我们讨论关于优化的想法！
  - type: textarea
    attributes:
      label: 请简要描述下做什么优化
    validations:
      required: true
  - type: textarea
    attributes:
      label: 对于实施该优化的方法的建议 (可选)
      placeholder: 建议我们如何实现这一点
    validations:
      required: false
